### sign up

@url_dev=http://localhost:3055/v1/api/

POST {{url_dev}}shop/sign-up
Content-Type: application/json

{
    "name": "Shop 112",
    "email": "abc1543@gmail.com",
    "password": "abc123"
}